### ISSUE TITLE
bug on /card command

### ISSUE THREAD

**Issue by Rofumer** [Extremelyd1/minecraft-bingo#82]
[15:17:16 INFO]: Max_Bel issued server command: /card
[15:17:16 ERROR]: Command exception: /card
org.bukkit.command.CommandException: Unhandled exception executing command 'card' in plugin MinecraftBingo v1.11.0
        at org.bukkit.command.PluginCommand.execute(PluginCommand.java:47) ~[paper-mojangapi-1.21.1-R0.1-SNAPSHOT.jar:?]
        at io.papermc.paper.command.brigadier.bukkit.BukkitCommandNode$BukkitBrigCommand.run(BukkitCommandNode.java:91) ~[paper-1.21.1.jar:1.21.1-132-b48403b]
        at com.mojang.brigadier.context.ContextChain.runExecutable(ContextChain.java:73) ~[brigadier-1.3.10.jar:?]
        at net.minecraft.commands.execution.tasks.ExecuteCommand.execute(ExecuteCommand.java:31) ~[paper-1.21.1.jar:1.21.1-132-b48403b]
        at net.minecraft.commands.execution.tasks.ExecuteCommand.execute(ExecuteCommand.java:19) ~[paper-1.21.1.jar:1.21.1-132-b48403b]
        at net.minecraft.commands.execution.UnboundEntryAction.lambda$bind$0(UnboundEntryAction.java:8) ~[paper-1.21.1.jar:1.21.1-132-b48403b]
        at net.minecraft.commands.execution.CommandQueueEntry.execute(CommandQueueEntry.java:5) ~[paper-1.21.1.jar:1.21.1-132-b48403b]
        at net.minecraft.commands.execution.ExecutionContext.runCommandQueue(ExecutionContext.java:103) ~[paper-1.21.1.jar:1.21.1-132-b48403b]
        at net.minecraft.commands.Commands.executeCommandInContext(Commands.java:443) ~[paper-1.21.1.jar:1.21.1-132-b48403b]
        at net.minecraft.commands.Commands.performCommand(Commands.java:350) ~[paper-1.21.1.jar:1.21.1-132-b48403b]
        at net.minecraft.commands.Commands.performCommand(Commands.java:337) ~[paper-1.21.1.jar:1.21.1-132-b48403b]
        at net.minecraft.commands.Commands.performCommand(Commands.java:332) ~[paper-1.21.1.jar:1.21.1-132-b48403b]
        at net.minecraft.server.network.ServerGamePacketListenerImpl.performUnsignedChatCommand(ServerGamePacketListenerImpl.java:2218) ~[paper-1.21.1.jar:1.21.1-132-b48403b]
        at net.minecraft.server.network.ServerGamePacketListenerImpl.lambda$handleChatCommand$11(ServerGamePacketListenerImpl.java:2192) ~[paper-1.21.1.jar:1.21.1-132-b48403b]
        at net.minecraft.server.TickTask.run(TickTask.java:18) ~[paper-1.21.1.jar:1.21.1-132-b48403b]
        at net.minecraft.util.thread.BlockableEventLoop.doRunTask(BlockableEventLoop.java:151) ~[paper-1.21.1.jar:1.21.1-132-b48403b]
        at net.minecraft.util.thread.ReentrantBlockableEventLoop.doRunTask(ReentrantBlockableEventLoop.java:24) ~[paper-1.21.1.jar:1.21.1-132-b48403b]
        at net.minecraft.server.MinecraftServer.doRunTask(MinecraftServer.java:1535) ~[paper-1.21.1.jar:1.21.1-132-b48403b]
        at net.minecraft.server.MinecraftServer.doRunTask(MinecraftServer.java:201) ~[paper-1.21.1.jar:1.21.1-132-b48403b]
        at net.minecraft.util.thread.BlockableEventLoop.pollTask(BlockableEventLoop.java:125) ~[paper-1.21.1.jar:1.21.1-132-b48403b]
        at net.minecraft.server.MinecraftServer.pollTaskInternal(MinecraftServer.java:1512) ~[paper-1.21.1.jar:1.21.1-132-b48403b]
        at net.minecraft.server.MinecraftServer.pollTask(MinecraftServer.java:1505) ~[paper-1.21.1.jar:1.21.1-132-b48403b]
        at net.minecraft.util.thread.BlockableEventLoop.managedBlock(BlockableEventLoop.java:135) ~[paper-1.21.1.jar:1.21.1-132-b48403b]
        at net.minecraft.server.MinecraftServer.managedBlock(MinecraftServer.java:1464) ~[paper-1.21.1.jar:1.21.1-132-b48403b]
        at net.minecraft.server.MinecraftServer.waitUntilNextTick(MinecraftServer.java:1471) ~[paper-1.21.1.jar:1.21.1-132-b48403b]
        at net.minecraft.server.MinecraftServer.runServer(MinecraftServer.java:1316) ~[paper-1.21.1.jar:1.21.1-132-b48403b]
        at net.minecraft.server.MinecraftServer.lambda$spin$0(MinecraftServer.java:329) ~[paper-1.21.1.jar:1.21.1-132-b48403b]
        at java.base/java.lang.Thread.run(Thread.java:1583) ~[?:?]
Caused by: java.lang.NullPointerException: Cannot invoke "com.extremelyd1.bingo.BingoCard.getBingoItems()" because "bingoCard" is null
        at MinecraftBingo-1.11.0.jar/com.extremelyd1.bingo.map.BingoCardItemFactory.drawBingoCardImage(BingoCardItemFactory.java:207) ~[MinecraftBingo-1.11.0.jar:?]
        at MinecraftBingo-1.11.0.jar/com.extremelyd1.bingo.map.BingoCardItemFactory.create(BingoCardItemFactory.java:119) ~[MinecraftBingo-1.11.0.jar:?]
        at MinecraftBingo-1.11.0.jar/com.extremelyd1.bingo.map.BingoCardItemFactory.create(BingoCardItemFactory.java:107) ~[MinecraftBingo-1.11.0.jar:?]
        at MinecraftBingo-1.11.0.jar/com.extremelyd1.command.CardCommand.onCommand(CardCommand.java:62) ~[MinecraftBingo-1.11.0.jar:?]
        at org.bukkit.command.PluginCommand.execute(PluginCommand.java:45) ~[paper-mojangapi-1.21.1-R0.1-SNAPSHOT.jar:?]
        ... 27 more

**Comment by Rofumer** [comment]
solved - incorrect files in https://github.com/Extremelyd1/minecraft-bingo/releases/download/v1.11.0/item_data.zip

**Comment by mr1cloud** [comment]
@Rofumer Hi, there is a problem, the archive with files is incorrectly packaged.

![image](https://github.com/user-attachments/assets/805e5727-5b42-400b-8de2-d6448b25a179)
